---
booktitle: Proceedings of The 36th International Conference on Algorithmic Learning
  Theory
shortname: ALT
volume: '272'
year: '2025'
start: &1 2025-02-24
end: 2025-02-27
published: 2025-02-17
conference_number: '36'
layout: proceedings
series: Proceedings of Machine Learning Research
publisher: PMLR
issn: 2640-3498
id: ALT-2025
month: 0
cycles: false
bibtex_editor: Kamath, Gautam and Loh, Po-Ling
editor:
- given: Gautam
  family: Kamath
- given: Po-Ling
  family: Loh
title: Proceedings of Machine Learning Research
description: |
  Proceedings of The 36th International Conference on Algorithmic Learning Theory
    Held in Politecnico di Milano, Milan, Italy on 24-27 February 2025

  Published as Volume 272 by the Proceedings of Machine Learning Research on 17 February 2025.

  Volume Edited by:
    Gautam Kamath
    Po-Ling Loh

  Series Editors:
    Neil D. Lawrence
date_str: 24--27 Feb
url: https://proceedings.mlr.press
author:
  name: PMLR
baseurl: "/v272"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
exclude:
- README.md
- Gemfile
- ".gitignore"
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: mlresearch/jekyll-theme
style: pmlr
permalink: "/:title.html"
ghub:
  edit: true
  repository: v272
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
  comments: false
volume_type: Volume
volume_dir: v272
email: ''
conference:
  name: Algorithmic Learning Theory
  url: http://algorithmiclearningtheory.org/alt2025/
  location: Politecnico di Milano, Milan, Italy
  dates:
  - *1
  - 2025-02-25
  - 2025-02-26
  - 2025-02-27
analytics:
  google:
    tracking_id: UA-92432422-1
orig_bibfile: "/Users/neil/mlresearch/v272/alt25.bib"
# Site settings
# Original source:  /Users/neil/mlresearch/v272/alt25.bib
